[project]
name = "catcv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.2.1",
    "pycryptodome>=3.22.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.1.0",
    "qrcode>=8.1",
    "segno>=1.6.6",
]
